name: obi CI for mobile

on:
  pull_request:
    branches: [master]
    paths:
      - 'mobile/**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./mobile

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: npm run build
        run: npm run build --if-present
        working-directory: ${{env.working-directory}}
      - name: npm test
        run: npm test
        working-directory: ${{env.working-directory}}
        env:
          CI: true
